cas:
  #Required properties
  server-url-prefix: https://login.dartmouth.edu/cas
  server-login-url: https://login.dartmouth.edu/cas/login
  client-host-url: http://localhost:8080

  #Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
  #request-wrapper-url-patterns: [/protected, /protected2]
  #assertion-thread-local-url-patterns: [/*]

  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  validation-type: CAS3

  #gateway: true
  use-session: true
  redirect-after-validation: true
  #allowed-proxy-chains: ['https://localhost:8443/proxy1', 'https://localhost:8443/proxy2']
  #proxy-callback-url: https://localhost:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true

casLogoutUrl: https://login.dartmouth.edu/cas/logout?service=http://localhost:8080

spring:
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

#Sample embedded servlet container SSL config and session tracking mode. Change as appropriate for your local deployment environment
server:
  port: 8080
  session:
    cookie:
      http-only: true
    tracking-modes: COOKIE
  # ssl:
  #   enabled: true
  #   key-store: /etc/cas/thekeystore
  #   key-store-password: changeit
  ssl:
    enabled: false
  #For 'renew' param, latest Java CAS client requires that it is set as the Servlet 'context-param'. This is how to easily set it in Spring Boot
  #context-parameters.renew: true


logging.level:
    org.jasig.cas: DEBUG
